services:
  postgres:
    image: postgres:18.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: plantuser
      POSTGRES_PASSWORD: plantpassword
      POSTGRES_DB: plantdb
    volumes:
      - pgdata:/var/lib/postgresql

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata: